//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You have a question ? You wish to contact me ? Feel free !.
        /// </summary>
        internal static string HOME_CONTACT_CONTACTME {
            get {
                return ResourceManager.GetString("HOME_CONTACT_CONTACTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome on my portfolio ! Enjoy your visit !.
        /// </summary>
        internal static string HOME_GREETING_MESSAGE {
            get {
                return ResourceManager.GetString("HOME_GREETING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string NAVBAR_MENUITEM_COMP {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me.
        /// </summary>
        internal static string NAVBAR_MENUITEM_CONTACT {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NAVBAR_MENUITEM_HOME {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string NAVBAR_MENUITEM_REAL {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string SEE_MORE {
            get {
                return ResourceManager.GetString("SEE_MORE", resourceCulture);
            }
        }
    }
}
