//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        internal static string CONTACT_YOURMAIL {
            get {
                return ResourceManager.GetString("CONTACT_YOURMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message.
        /// </summary>
        internal static string CONTACT_YOURMESSAGE {
            get {
                return ResourceManager.GetString("CONTACT_YOURMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download my CV.
        /// </summary>
        internal static string CV_DOWNLOAD_CV {
            get {
                return ResourceManager.GetString("CV_DOWNLOAD_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or check it out online (Adobe Reader required).
        /// </summary>
        internal static string CV_SEEONLINE {
            get {
                return ResourceManager.GetString("CV_SEEONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string GENERAL_SUBMIT {
            get {
                return ResourceManager.GetString("GENERAL_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string HOME_ABOUT_ME {
            get {
                return ResourceManager.GetString("HOME_ABOUT_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You have a question ? You wish to contact me ? Feel free !.
        /// </summary>
        internal static string HOME_CONTACT_CONTACTME {
            get {
                return ResourceManager.GetString("HOME_CONTACT_CONTACTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome on my portfolio ! My name is Stéphane Miginiac, I&apos;m 25, french, and student in my fifth and last year at Intech&apos;Info.
        ///    I&apos;ve always been passionate about new technologies which is why I decided to study computer engineering after obtaining my Baccalauréat.
        ///    After some years of doubts, I finally joined Intech&apos;Info school, which has the advantage of combining theoretical classes and more practical classes.
        ///  And here I am, after 3 years of classes, 6 months of internship and 2 years of apprent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HOME_GREETING_MESSAGE {
            get {
                return ResourceManager.GetString("HOME_GREETING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My personality radar.
        /// </summary>
        internal static string HOME_PERSONALITY_RADAR {
            get {
                return ResourceManager.GetString("HOME_PERSONALITY_RADAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Talent ID.
        /// </summary>
        internal static string HOME_TALENT_ID {
            get {
                return ResourceManager.GetString("HOME_TALENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string NAVBAR_MENUITEM_COMP {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me.
        /// </summary>
        internal static string NAVBAR_MENUITEM_CONTACT {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NAVBAR_MENUITEM_HOME {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string NAVBAR_MENUITEM_REAL {
            get {
                return ResourceManager.GetString("NAVBAR_MENUITEM_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string SEE_MORE {
            get {
                return ResourceManager.GetString("SEE_MORE", resourceCulture);
            }
        }
    }
}
