//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competence
    {
        public Competence()
        {
            this.CompetenceByRealisations = new HashSet<CompetenceByRealisation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompetenceType { get; set; }
    
        public virtual ICollection<CompetenceByRealisation> CompetenceByRealisations { get; set; }
    }
}
