
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObjectModel.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Competence
{

    public Competence()
    {

        this.Realisations = new HashSet<Realisation>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Nullable<int> CompetenceType { get; set; }

    public string LogoUrl { get; set; }



    public virtual ICollection<Realisation> Realisations { get; set; }

}

}
