
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObjectModel.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Realisation
{

    public Realisation()
    {

        this.Competences = new HashSet<Competence>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string LogoName { get; set; }



    public virtual ICollection<Competence> Competences { get; set; }

}

}
